repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.23.3
    hooks:
      - id: check-github-actions
      - id: check-github-workflows

  - repo: local
    hooks:
      - id: update-readme-help
        name: Update README help
        entry: ./scripts/update-readme-help.sh
        language: script
        files: ^(README.md|aws_adfs/(commands|list_profiles|login|reset).py)$
